### ISSUE TITLE
PoA packaging workflow to rely on S3 notifications

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#1019]
This issue is a more detailed list of actions to finish point 1 on issue https://github.com/elifesciences/elife-bot/issues/565, where the end goal is to remove all dependence on SimpleDB.

The proposed new PoA packaging procedure in summary:
- a PoA `.zip` file input arrives into the `elife-ejp-poa-delivery` bucket
- results in an S3 notification, which is added to a new SQS queue, the queue having a lengthy message retention time (between 4 and 14 days we're thinking)
- daily a the `cron.py` initiates the PoA packaging workflows at a specific time (this already happens currently)
- for each message in the queue, start a `PackagePOA` workflow for each `.zip` file (this happens now, but the list of `.zip` files is taken from SimpleDB data from S3 bucket polling)

Steps to completion:
- [x] create new SQS queue with long message retention time (@giorgiosironi) - possibly named `poa-incoming-queue`
- [x] add S3 notification configuration to the `elife-ejp-poa-delivery` bucket manually (@giorgiosironi)
- [x] (optional) mirror the `elife-ejp-poa-delivery` S3 notification settings in the builder / infrastructure definitions (@giorgiosironi)
- [x] refactor the existing `starter/cron_NewS3POA.py` file to use SQS queue data instead of SimpleDB data for getting PoA `.zip` file names
- [x] Note: prior to deploying this new PoA logic to `prod` environment, may want to clear out the existing SQS messages so the files do not get processed again

I considered to try and integrate with existing SQS queue listeners use in the article ingest workflows, but since those are all based around processing SQS messages immediately upon receiving them, I think keeping the delayed PoA packaging logic separate from those is probably less messy. There may be some connection and message processing logic that can be consolidated.

The first three steps @giorgiosironi if you could please lend some help on setting up queues and infrastructure? I'm happy to give it a go, but you may have suggestions and requirements I'm not fully aware of. Thanks!

**Comment by gnott** [comment]
Suggestion of new queue name: `poa-incoming-queue`

**Comment by giorgiosironi** [comment]
> since those are all based around processing SQS messages immediately upon receiving them, I think keeping the delayed PoA packaging logic separate from those is probably less messy.

Yes.

**Comment by giorgiosironi** [comment]
Review https://github.com/elifesciences/builder/pull/606 which will apply queue and notifications to `end2end` and `continuumtest`; plus create the queue only on prod.

After that we can manually replicate the notifications on `prod`, since the bucket there is not managed and hence must be modified manually.

**Comment by gnott** [comment]
Confirming, the `prod` bucket configuratio is looking good. The `prod-poa-incoming-queue` currently has three S3 notification messages available. It also includes a `s3:TestEvent` message, the earliest one, which could be something AWS sends when it is first configured? Interesting, but unimportant for the PoA plan. Thanks @giorgiosironi for this configuration!

I will continue with the logic to turn these S3 notifications into `PackagePOA` workflows as the time specified in the `cron.py`.
