### ISSUE TITLE
log elife-bot email out to files so the content can be harvested and monitored, send error/warning emails only.

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/elife-bot#108]
The elife-bot sends us emails with the below information. 
I would like to capture this sort of information and also reduce email noise to the point where only warnings and errors are sent to us, typically only by the application monitoring the logs.

What I would like is to have the below data as a csv or json or some sort of structured
data output to the /var/log dir where I can target it and parse it and send it off to the monitor.
###### 

A short history of workflow executions
As at 2014-11-30T15:45:04.000Z
Time period: 14400 seconds
Domain: Publish

CANCELED: 0
COMPLETED: 85
CONTINUED_AS_NEW: 0
FAILED: 0
TERMINATED: 0
TIMED_OUT: 0

Sincerely

eLife bot
######

**Comment by gnott** [comment]
We generally rely on monitoring operations with NewRelic, and then we can look up in the SWF workflow execution history _ad hoc_ if we want to. Other failed or timed out workflows are noticed by people who depend on a result and are either emailed an error, a dashboard displays and error, or they notice an omission of output files.

**Comment by lsh-0** [comment]
wow this ticket is old. I had such high dreams for a monitoring utopia. Instead we settled for a hodge podge.
