### ISSUE TITLE
Replacement for SimpleDB

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#565]
Here is my proposal for how to remove SimpleDB as a requirement in the `elife-bot` project.

A very brief update: Some of the parts that depended on SimpleDB have been removed, but some still remain. For a while I thought about how the state could be stored elsewhere, only recently I think the combination of logic and data available makes it possible to remove what SimpleDB provides entirely from the project.

The proposed solution comes as three major parts, which can be done separately and/or concurrently, and can also be tracked in other tickets for each of the ~three~ four parts. These parts are:

1. Change the PoA packaging workflow to rely on S3 notifications instead of polling S3 buckets
2. `PublicationEmail` to be switched over to explicit email sending logic instead of relying on duplicate email checking
3. Send all the emails from the bot directly as SMTP mails, and do away with the email sending queue
4. Remove all references to the `simpleDB` provider in all other code

Todos:

- [x] Remove bucket polling in favour of S3 notifications for PoA workflow
- [x] Refactor and switch over PublicationEmail to use SMTP sending and different way to not send duplicates
- [x] Replace all places emails are added to the email queue to instead send emails immediately by SMTP - Ticket https://github.com/elifesciences/elife-bot/issues/854
- [x] Remove all remaining `simpleDB` provider imports in any other files, and then delete the `simpleDB.py` module
- [x] Remove any documentation in the project about SimpleDB
- [x] Can probably remove `settings.prefix` and `settings.delimiter` from `settings.py`, which I think was only used by SimpleDB logic

A little more about each of these solution parts for discussion, which can be duplicated over to their own tickets later.

**1. Change the PoA packaging workflow**
The last thing that relies on S3 bucket polling data is the PoA packaging workflow. It is run once a day at a particular time of day. At that time, it queries SimpleDB records to find the files that have been uploaded in the past 24 hours, and processes those.

My suggested solution is:
* enable S3 notifications on the bucket the receives these PoA zip files
* send those notifications to a new SQS queue (@giorgiosironi if you could please comment and help with infrastructure to create the queue and config)
* A new, separate, PoA queue listener will get messages from this queue when it intends to process the zip files, currently only once a day, at a particular time as specified in the `cron.py`. (In future we can package the files more than once a day, but again only at particular times, due to synchronicity with the `.csv` files also required).

Essentially saving state, but only for a limited time, of what files arrived, so the messages on the queue would ideally stay in flight for at least 72 hours, maybe 7 days might be safe.

**2. `PublicationEmail` change**
Right now, any article that is published will invoke the `PublicationEmail` activity. But, so that we do not send the same type of email twice for the same article to the same recipient, it still relies on the history of emails sent, stored in SimpleDB, to determine whether it would be a first send or a duplicate email.

Recently the logic in the bot providers is smart enough to figure out if it was the `first PoA version` or `first VoR version` that was just published, and it is also aware of whether the workflow was part of a silent correction. Given these shreds of data, the "only send one type of email once" logic in `PublicationEmail` can be expressed as a set of rules for when to send and when not to send. 

Very little would be lost if the email duplication logic is gone, and the case can be made that it is much better for everyone without expecting to find a complete history of all emails sent in the past to determine whether an email is a duplicate. It also completely removes the requirement to have the SimpleDB for emails there.

**3 Send all the emails as SMTP**
Most of the emails sent by the `elife-bot` uses the email sending queue I originally created, which relies on SimpleDB. Emails are put in the queue by various activities, and then the `SendQueuedEmail` activity sends them, which is invoked every five minutes.

When we built the digest workflows, we added SMTP email sending ability (because we wanted to send email attachments, which boto SES would not support). So, we have the option to switch all the spots that `"queue"` an email over to `"send by SMTP immediately"` emails.

Based on the volume of mails we send, probably not exceeding 100 emails at a time (the most probably sent by `PublicationEmail`), we can probably send in real time instead of using the old queue system.

The email queue, as it is, also supports sending emails that are scheduled for a future date, but we never ended up using it in this way.

If keeping some sort of email queue might still be a good idea, we can use some other method to rapidly queue emails so workflows will not be held up by sending email. Other ideas for sending emai that doesn't require SimpleDB are welcome for suggestions.

@giorgiosironi and @GiancarloFusiello this is a summary of the big master plan to remove SimpleDB.

**Comment by gnott** [comment]
It's been longer than I remember since I described this, it seems like only yesterday! Anyway, I still feel this is a good course of action and I will be doing it.

**Comment by gnott** [comment]
Another benefit to refactoring away all that SimpleDB provides is we do not need to copy any data over to a new data store, all the old data is not required going forward.

**Comment by gnott** [comment]
@giorgiosironi, when time allows, I would very much appreciate if you could read point 1 in the above, concerning S3 notifications from another bucket, and potentially to a new SQS queue and a new python listener, specifically for PoA zip deposits.

I'm open to alternative suggestions on how to notice a new object in an S3 bucket, but delay the processing of it to a specific time of day.

**Comment by giorgiosironi** [comment]
We have good support for adding buckets and SQS notifications:
https://github.com/elifesciences/builder/blob/master/projects/elife.yaml#L820-L823
It would be ideal to do this on a new bucket that we can put in there, but if it's an existing bucket we will leave it commented out in the `prod` section, c'est la vie.

Message retention on SQS is up to [14 days](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-limits.html) but it's not the default (4 days), we'll have to tweak the settings to push it up; it's a property of the queue.

You may also need a longer visibility timeout if it takes long to process a single file e.g. sending many emails or waiting for many workflows to finish.

**Comment by gnott** [comment]
I feel like using the exiting bucket might be preferable, then EJP doesn't have to change anything.

As an alternative, I'm also thinking we could have it check for zip files added in the previous 24 hour period (with no S3 notifications and no SQS), but the tradeoff would be we'd be stuck to only running PoA packaging once a day. We only do it once a day now, but the notification -> SQS would mean we could increase that to multiple times a day if we choose to in the future (still based on a time clock, since EJP sends CSV files hourly, some hours of the day).

Good notes about retention and visibility, some important details for the final plan.

**Comment by gnott** [comment]
Refactoring of `PublicationEmail` was completed and deployed last week. 1 of 3 todos completed.

**Comment by gnott** [comment]
Merged `elife-bot` PR to deploy the new PoA SQS queue notification method.

Next step is I can start to dismantle and delete all mentions of SimpleDB!

**Comment by gnott** [comment]
Pending deployment of the code to `prod`, but this issue is done!
