### ISSUE TITLE
Track whether is a silent correction or not in the workflow session

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#683]
The ``PublicationEmail`` activity sends emails to authors when an article is published. It has duplicate email checking logic, so a recipient would never receive the same email twice. 

However, as a side effect of some silent corrections, occasionally an email is sent to one author. I think this happens if an author adds or changes their email address since the last time the emails were sent. Since this new email address is not in the duplicate email checking log, then the activity sends an email to the author.

One suggestion for an improvement could be in the ``ScheduleDownstream`` activity - which is part of the ``PostPerfectPublication`` workflow - to not queue the article for ``PublicationEmail`` if the article supplied was a silent correction. Currently the ``PostPerfectPublication`` workflow is not aware whether it was part of a silent correction or a normal publication event. If we know it was a result of a silent correction then we can modify its logic accordingly. It could get the value from the workflow session data.

There are a couple potential markers for a silent correction in the data supplied at the start of a ``SilentCorrectionIngest`` workflow (https://github.com/elifesciences/elife-bot/blob/develop/starter/starter_SilentCorrectionsIngest.py#L32)

```
        input['version_lookup_function'] = "article_highest_version"
        input['force'] = True
```

The values of both ``version_lookup_function`` and ``force`` indicate a silent correction, although we do not have a specific value to represent a silent correction, for example if we had ``silent_correction = True`` it would be explicit. The two values above are also not stored in the session yet anyway, although they are passed between Lax and the publication approval (I think) we could store them in the session from the beginning.

Should we track the silent correction status in the workflow session somewhere? And/or, should we track the ``version_lookup_function`` and ``force`` values and then use those as proxies for whether it was part of a silent correction? Some input from @giorgiosironi, @seanwiseman, @Jenniferstrej or @jhroot  would be much appreciated - thanks!

**Comment by giorgiosironi** [comment]
>  if we had silent_correction = True it would be explicit

:+1: for being explicit - the `version_lookup_function` values or even that parameter's name may change, but a ~~diamond~~ specific configuration is forever

> The two values above are also not stored in the session yet anyway, although they are passed between Lax and the publication approval (I think) we could store them in the session from the beginning.

It looks like you need to store in the session this new `silent_correction` so that it is persisted along the whole run even for more than one workflow; if that's the case, no problem with that.

To make this a bit more future-proof, rather than a boolean parameter a `run_type=silent_correction` could be used. That leaves space for other possible `run_type`s to be introduced.

**Comment by gnott** [comment]
Thanks @giorgiosironi - I like the session variable name ``run_type`` - much more useful.
