### ISSUE TITLE
ScheduleCrossref for silent correction workflow, only do for the most recent article version

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#692]
``ScheduleCrossref`` activity was removed from the ``SilentCorrectionProcess`` workflow (in PR https://github.com/elifesciences/elife-bot/pull/507) when the features of the Crossref deposit were expanded. The deposit data included citations, data and text mining files, etc. If an older version was silently corrected, then Crossref may overwrite the most recent version data with older, incomplete data from a PoA article, for example.

The proposed improvement is in ``ScheduleCrossref`` to only schedule an article for Crossref deposit in a silent correction if it a silent correction of the most recent published version of the article. Any version previous to the currently published version would not be scheduled for Crossref deposit.

Could be related to issue https://github.com/elifesciences/elife-bot/issues/683 that would allow the logic to check the type of workflow being run as part of the conditional logic.

It is also possible (I think) for the logic to be compatible with silent correction and non-silent correction workflows: only schedule for Crossref deposit if it is the currently published version or greater than the published version (for ingest of new versions), or if no version exists (for ingest of v1 articles).

There is already some pub date embargo logic in the ``DepositCrossref`` workflow itself, which holds back any v1 article from being deposited until on its pub date and not before its pub date, to allow for ingesting articles early and scheduling them for coordinated press events.

@giorgiosironi @seanwiseman you may have comments on my thinking here and whether it is a good solution.

**Comment by giorgiosironi** [comment]
bq. It is also possible (I think) for the logic to be compatible with silent correction and non-silent correction workflows: only schedule for Crossref deposit if it is the currently published version or greater than the published version (for ingest of new versions), or if no version exists (for ingest of v1 articles).

Need to enumerate the different scenarios, but this seems sound to me. I now understand what was the problem with blindly depositing to Crossref every silent correction.

**Comment by gnott** [comment]
Also a possible task for @GiancarloFusiello if you're interested.

**Comment by gnott** [comment]
I am going to pick up this issue now, along with some proposed `DepositCrossref` refactoring (for which I will create a new issue).
