### ISSUE TITLE
GithubException raised in UpdateRepository activity updating an existing XML file

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#707]
As part of Major Subject Area silent corrections for eLife articles run yesterday, and after a subject tag confirmation procedure, the XML file ``elife-06416-v1.xml`` (https://github.com/elifesciences/elife-article-xml/blob/master/articles/elife-06416-v1.xml) was not updated in the git repo.

In the ``worker.log``, the activity logs a ``GithubException`` and some details. As @giorgiosironi pointed out, it probably stems from line https://github.com/elifesciences/elife-bot/blob/develop/activity/activity_UpdateRepository.py#L112 where it invokes ``get_contents()`` of the pyGithub module.

Indications are the file is too big for ``get_contents()``. A similar issue (https://github.com/PyGithub/PyGithub/issues/661) and in the documentation at https://developer.github.com/v3/repos/contents/, it states ``"This API supports files up to 1 megabyte in size."``. According to the Github page for ``elife-06416-v1.xml`` it is 1.3 MB.

If we want to support updating files greater than 1 MB, it may require the logic in ``UpdateRepository`` to not rely on ``get_contents()``. I didn't look in depth at solutions and I further reading should describe how to use the tree and/or sha values to update a file without getting its contents.

@giorgiosironi, @seanwiseman or anyone with comments please share them here.

**Comment by giorgiosironi** [comment]
The error message should definitely be improved as it seems to be about a missing `sha`. It could come from the library itself however (but we can catch it, and produce a better exception).

I agree in theory you could use a read API to get the `sha` so that you can use a write API to update the file with the new content. I don't have an estimation on how difficult this would be however.

**Comment by gnott** [comment]
Considering the rarity of this exception, which seems to be when updating an eLife XML file that is larger than 1 MB in size in a Github repository, and how the 1 MB restriction is imposed by the Github API, at this time we'll consider this issue suitable to close as "not done". If it comes up again we can open a new issue.
