### ISSUE TITLE
Simplify the activity VerifyPublishResponse logic

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#710]
There is some older logic in https://github.com/elifesciences/elife-bot/blob/develop/activity/activity_VerifyPublishResponse.py  based on the setting ``publication_authority`` value, which was either ``journal`` or ``elife-website``. Now that all EIF file logic is removed, we also should not need to use the ``elife-website`` publication authority again. The activity can be simplified to no longer consider the ``elife-website``.

@giorgiosironi I hope this sounds like a good idea. Do you think we should keep the ``publication_authority``  in the settings for potential future use? Or can the value also be removed?

**Comment by giorgiosironi** [comment]
> we also should not need to use the elife-website publication authority again. The activity can be simplified to no longer consider the elife-website.

Agreed, go for it and remove what's obsolete

> Do you think we should keep the publication_authority in the settings for potential future use? Or can the value also be removed?

It's uncertain enough that it should be removed, and if we need something similar in the future we'll add another setting.
