### ISSUE TITLE
Increase test coverage on some activity objects

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#827]
When refactoring some activity code, there were some activity objects with no automated test cases at all. Seven of these can use at least some basic tests to check for library imports or typos at a minimum:

- [x] Basic automated tests for `activity/activity_AdminEmailHistory.py`
- [x] Automated tests and refactor storage_context for `activity/activity_ArchiveArticle.py`
- [x] Basic automated tests for `activity/activity_PingWorker.py`
- [x] Basic automated tests for `activity/activity_S3Monitor.py`
- [x] Basic automated tests for `activity/activity_ScheduleDownstream.py`
- [x] Basic automated tests for `activity/activity_SendQueuedEmail.py`
- [x] Basic automated tests for `activity/activity_VersionReasonDecider.py`
- [x] Increase test coverage for `activity/activity_PubRouterDeposit.py` (currently 20% coverage)
- [x] `activity/activity_Sum.py` also has no tests, but I am suggesting to delete it entirely.

**Comment by giorgiosironi** [comment]
FWIW the more you can extract into a `provider` (not tied to SWF) the easier it will be to test and incidentally to reuse across activities.

**Comment by gnott** [comment]
I was hoping to add some quick tests to be more confident all the Python 3 compatibility can be checked. 

After trying this on `ArchiveArticle` it was not that easy, and some refactoring to use the `storage_context` will be an improvement there, instead of using S3 and bucket keys directly. So some refactoring might be another good output from the attempt for test coverage.

These will probably be best added as a separate PR for each activity, otherwise it will take too long to get all these done in one branch.

**Comment by gnott** [comment]
I think all activities have at least some tests now, fairly good coverage on many of them. The motivation of this issue for me was to make sure the Python 3 compatibility effort had the best chance of finding all the potential problems when running automated tests, rather than having gaping holes in the coverage.
