### ISSUE TITLE
CopyGlencoeStillImages require Glencoe metadata for XML with videos

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#912]
A small improvement proposed to overcome video still image errors, related to https://github.com/elifesciences/issues/issues/4907.

In article publishing workflows we verify Glencoe metadata exists in the `VerifyGlencoe` activity, however due to coordination of resupplying videos as part of a new ingest run, the video metadata can disappear for a short time while Glencoe processes video files. If the metadata is missing by the time the `CopyGlencoeStillImages` activity happens, then it does not find any video still images, the images do not end up in the CDN bucket, ultimately leading to a validation error in Lax when checking the article JSON.

The small improvement is to add into the `CopyGlencoeStillImages` activity a verify and retry logic, similar to the code in https://github.com/elifesciences/elife-bot/blob/develop/activity/activity_VerifyGlencoe.py#L74-L79, the key logic being

```
            time.sleep(60)
            return self.ACTIVITY_TEMPORARY_FAILURE
```

The sleep time will allow Glencoe to transcode the new video deposit. The `self.ACTIVITY_TEMPORARY_FAILURE` will result in repeating the `CopyGlencoeStillImages` activity 60 seconds later, when hopefully it will work.

As part of this, `CopyGlencoeStillImages` should also be made to read the article XML, and if there are videos in the XML, then it will require a non-404 response from the Glencoe metadata request, otherwise it will sleep and then retry later.

@giorgiosironi I wonder if you could please read this proposal and see if the logic is a good idea as written?

It would render `VerifyGlencoe` almost useless since `CopyGlencoeStillImages` would practically fill that role after the change.

**Comment by giorgiosironi** [comment]
I agree this would be more robust in retrying. Not sure I fully understand the retry conditions but replicating the behavior from `VerifyGlencoe` is a good start.

**Comment by gnott** [comment]
I wasn't sure about when the retry happens either, presumably it is when an exception is raised, possibly a `404` response from the Glencoe resource. I might also clarify the logic for retry if it can be clearer in both activities.

**Comment by gnott** [comment]
In the end, the activity will now return `self.ACTIVITY_TEMPORARY_FAILURE` if the XML has videos, but Glencoe says it does not have videos. This will result in a default 10 second sleep of a bot decider before the activity is tried again. This will avoid the immediate `self.ACTIVITY_PERMANENT_FAILURE` which causes the workflow to stop when this same situation was encountered in the past.

The activity code is refactored as well. It is (hopefully) slightly easier to understand, however due to integrating with a third party API and multiple situations for poa/vor or standlone/publishing-workflow, and how end events are specified to the dashboard, it still remains slightly complex.

I am going to merge it, since the automated tests are green, and I hope it will pass end-to-end testing.
