### ISSUE TITLE
PublicationEmail change logic of when to send emails

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#921]
Part 2 in the plan to not use SimpleDB anymore (https://github.com/elifesciences/elife-bot/issues/565), it includes a change to the `PublicationEmail` activity.

Instead of relying on the SImpleDB data to determine which emails were sent already, change the logic of when to send emails to look at the article type, status, and whether it is the "first vor" to determine when to send publication emails.

More changes as part of clean up
- [x] Change the logic for when to send what email (the basis of this issue) - defined as only the first version of each status (first poa or first vor)
- [x] To handle silent correction logic, put this into the `ScheduleDownstream` activity, because we can rely on the workflow session value there. Once it is queued as a `PublicationEmail`, we do not know whether the XML was part of a silent correction or not
- [x] Send emails directly by SMTP instead of using the SimpleDB email queue
- [x] Remove `get_editors()`, it is not used
- [x] Remove `send_email_testrun()` and other test run logic, we haven't used this recently
- [x] Remove logic for potentially sending duplicate emails, we don't use this, it was only for testing purposes
- [x] Switch all direct S3 bucket usage over to `storage_context` / `storage_provider`
- [x] Refactoring and increase test coverage, where possible
- [x] Linting code (as usual)
- [x] **Deployment note:** make sure the S3 outbox folder is empty when deploying this new logic, otherwise some duplicate emails will get sent for those articles in the outbox (actually on looking at it, only article types that we do not send to remain in the outbox, all other articles are cleared each day, but it is probably good to check the outbox contents when deploying to be sure)

**Comment by gnott** [comment]
Regarding articles of type `Insight`, I thought the new logic might not work, but after further thought it might afterall.

We send emails about Insight articles as two types:

1. VoR and Insight is published on the same day: we can send them the VoR is published email, with another paragraph shown that says "and Insight was also published..."
2. If the Insight is published later: we send a "An Insight was published about your article" email

The new logic can work properly if when there is an Insight article to send, to check whether it is the first VoR of the Insight. If there is no research article in the same batch, then send the "An Insight was published..." email.

If there's a VoR and an Insight in the same batch, it can still send the template as described in point 1 above.

Make sure the test scenarios include these situations. I think the existing ones may already represent them, except for the non-first-VoR Insight article situation.

**Comment by gnott** [comment]
In the logic for determining whether the article is the first `poa` or first `vor` article, and only sending emails for those. there's a tiny potential glitch: if two versions of an article are published in the same day, i.e. before the `PublicationEmail` workflow is run, then those authors will not receive an email, since the most recent version is not the first version.

I could possibly move this logic over the `ScheduleDownstream` activity (which I had to do in the case of silent correction workflows, since the original workflow session data is not available later on when `PublicationEmail` runs at the end of the day). Moving there is an option, however then the logic for when to send gets spread out even further.

For now, I'll opt for the logic goes into `PublicationEmail`, and if two versions of an article is published on the same day, then emails are not sent to those authors.

CCing in @giorgiosironi so someone else is vaguely aware of the logic decision I'm making here.

**Comment by giorgiosironi** [comment]
> if two versions of an article are published in the same day

I agree it's a tiny scenario. Let's revisit if it ever breaks or if there are similar cases of logic being in the wrong place.

**Comment by gnott** [comment]
I've had a re-think about the `"when to send"` logic of the publication emails two comments above: 

I am now intending to put the `"send/do not send"` decision making logic into `ScheduleDownstream`, since it is a direct result of a publication workflow and the session there. Then there is no confusion about which version results in an email and whether it was part of a silent correction.

Then, `PublicationEmail` will only be concerned with selecting the recipient email addresses and which email template to use. It will send an email for any article that is present in the `"outbox"` folder (which is a crude S3 based queue).

I wanted to mention it here and cc in @giorgiosironi to be aware of my changed opinion, and whether you have any objections to it.

**Comment by giorgiosironi** [comment]
> I am now intending to put the "send/do not send" decision making logic into ScheduleDownstream, since it is a direct result of a publication workflow and the session there

This seems like the preferred option, deciding as early as possible and it favors cohesion as the data to decide are available in that activity. If circumstances have changed and we can go for this, all the better.

**Comment by gnott** [comment]
Merged the code changes, I will deploy when all tests are green and the branch is deployable.

**Comment by gnott** [comment]
I had to debug in the new environment, and the above PR will fix getting a list of S3 objects from the outbox folder. It was not getting any XML files to run, because the path had a trailing `/` character, which the storage provider does not accept.
