### ISSUE TITLE
Investigate emit_monitor_event refactoring

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#982]
As suggested in comment https://github.com/elifesciences/elife-bot/pull/981#discussion_r348382848

Frequent use of the `self.emit_monitor_event()` by Activity objects could reduce code complexity. Please see the original comment if my statement is not correct.

Todos

- [ ] Investigate using context manager logic using `with` statement
- [ ] Does this result in better exception catching and log / message content?
- [ ] Add more details here and todo steps as required
- [ ] Define an explicit set of guidelines to follow when emitting messages

**Comment by giorgiosironi** [comment]
Just saying this should not be a blocker for the related PR, otherwise we shouldn't have created a separate ticket. See it as an improvement that can simplify the code of many activities, so it has a larger scopre.

**Comment by gnott** [comment]
Due to project priorities, I will close this issue. It is a code clean up / refactor, and other things take precedence.
